import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#dcecff',
  },
  app: {
    flex: 1,
    backgroundColor: '#dcecff',
    maxWidth: 430,
    width: '100%',
    alignSelf: 'center',
  },
  content: {
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 118,
  },
  topBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  kicker: {
    color: '#5f718f',
    fontSize: 15,
    fontWeight: '700',
  },
  heroTitle: {
    color: '#13233b',
    fontSize: 42,
    fontWeight: '800',
    letterSpacing: 0,
    marginTop: 2,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#edf5ff',
    borderColor: 'rgba(255,255,255,0.8)',
    borderRadius: 24,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    boxShadow: '0 10px 18px rgba(117,146,185,0.16)',
    width: 48,
  },
  avatarText: {
    color: '#1d73df',
    fontSize: 18,
    fontWeight: '800',
  },
  practicePanel: {
    backgroundColor: 'rgba(247,251,255,0.82)',
    borderRadius: 28,
    padding: 22,
    boxShadow: '0 16px 26px rgba(142,169,201,0.18)',
  },
  softIcon: {
    alignItems: 'center',
    backgroundColor: '#e5f0ff',
    borderRadius: 20,
    height: 42,
    justifyContent: 'center',
    marginBottom: 16,
    width: 42,
  },
  softIconText: {
    color: '#1f76e8',
    fontSize: 18,
    fontWeight: '800',
  },
  panelTitle: {
    color: '#17233a',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  panelText: {
    color: '#63728a',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  planMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 16,
  },
  planMeta: {
    backgroundColor: '#edf5ff',
    borderRadius: 14,
    color: '#1976ee',
    fontSize: 12,
    fontWeight: '900',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  sectionHeader: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 28,
  },
  sectionTitle: {
    color: '#17233a',
    fontSize: 21,
    fontWeight: '800',
  },
  sectionHint: {
    color: '#74839a',
    fontSize: 13,
    fontWeight: '700',
  },
  moodRow: {
    backgroundColor: 'rgba(247,251,255,0.72)',
    borderRadius: 24,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  moodButton: {
    alignItems: 'center',
    backgroundColor: '#e5edf8',
    borderRadius: 18,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  moodButtonActive: {
    backgroundColor: '#1976ee',
  },
  moodButtonText: {
    color: '#6e7c91',
    fontSize: 18,
    fontWeight: '800',
  },
  moodButtonTextActive: {
    color: '#ffffff',
  },
  scenarioGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  scenarioTile: {
    backgroundColor: 'rgba(247,251,255,0.78)',
    borderRadius: 24,
    minHeight: 154,
    padding: 16,
    width: '48%',
  },
  scenarioTitle: {
    color: '#17233a',
    fontSize: 17,
    fontWeight: '800',
  },
  scenarioSubtitle: {
    color: '#697890',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },
  memoryPanel: {
    backgroundColor: 'rgba(247,251,255,0.68)',
    borderRadius: 26,
    marginTop: 24,
    padding: 20,
  },
  progressPanel: {
    backgroundColor: 'rgba(247,251,255,0.72)',
    borderRadius: 26,
    marginTop: 16,
    padding: 18,
  },
  progressHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  linkText: {
    color: '#1976ee',
    fontSize: 14,
    fontWeight: '800',
  },
  progressGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  progressCell: {
    backgroundColor: '#edf5ff',
    borderRadius: 18,
    flex: 1,
    minHeight: 74,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  progressValue: {
    color: '#17233a',
    fontSize: 18,
    fontWeight: '900',
  },
  progressLabel: {
    color: '#6e7d94',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 4,
  },
  talkPanel: {
    alignItems: 'center',
    backgroundColor: '#17233a',
    borderRadius: 26,
    flexDirection: 'row',
    marginTop: 14,
    padding: 18,
  },
  talkDot: {
    alignItems: 'center',
    backgroundColor: '#8fc0ff',
    borderRadius: 20,
    height: 42,
    justifyContent: 'center',
    marginRight: 14,
    width: 42,
  },
  talkDotText: {
    color: '#17233a',
    fontSize: 20,
    fontWeight: '900',
  },
  talkCopy: {
    flex: 1,
  },
  talkTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  talkText: {
    color: '#cfe1ff',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 5,
  },
  safetyStrip: {
    backgroundColor: '#fff2ed',
    borderColor: '#ffc4ad',
    borderRadius: 22,
    borderWidth: 1,
    marginTop: 14,
    padding: 16,
  },
  safetyStripTitle: {
    color: '#9f3d21',
    fontSize: 16,
    fontWeight: '900',
  },
  safetyStripText: {
    color: '#7a584d',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 5,
  },
  chatScreen: {
    flex: 1,
  },
  chatContent: {
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 180,
  },
  quickPromptRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 18,
  },
  quickPrompt: {
    backgroundColor: 'rgba(247,251,255,0.8)',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  quickPromptText: {
    color: '#1976ee',
    fontSize: 13,
    fontWeight: '800',
  },
  quickPromptAlert: {
    backgroundColor: '#fff2ed',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  quickPromptAlertText: {
    color: '#d65b36',
    fontSize: 13,
    fontWeight: '900',
  },
  chatSafetyPanel: {
    backgroundColor: '#fff2ed',
    borderColor: '#ffc4ad',
    borderRadius: 22,
    borderWidth: 1,
    marginBottom: 16,
    padding: 16,
  },
  chatSafetyTitle: {
    color: '#9f3d21',
    fontSize: 17,
    fontWeight: '900',
  },
  chatSafetyText: {
    color: '#7a584d',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  chatBubble: {
    borderRadius: 24,
    marginBottom: 10,
    maxWidth: '88%',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  assistantBubble: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(247,251,255,0.82)',
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#1976ee',
  },
  chatBubbleText: {
    color: '#52627a',
    fontSize: 15,
    lineHeight: 22,
  },
  userBubbleText: {
    color: '#ffffff',
  },
  chatComposer: {
    alignItems: 'flex-end',
    alignSelf: 'center',
    backgroundColor: 'rgba(247,251,255,0.95)',
    borderRadius: 28,
    bottom: 98,
    flexDirection: 'row',
    gap: 10,
    left: 22,
    maxWidth: 386,
    padding: 10,
    position: 'absolute',
    right: 22,
    boxShadow: '0 14px 24px rgba(142,169,201,0.2)',
  },
  chatInput: {
    color: '#17233a',
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
    maxHeight: 92,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sendButton: {
    alignItems: 'center',
    backgroundColor: '#1976ee',
    borderRadius: 21,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  sendButtonText: {
    color: '#ffffff',
    fontSize: 23,
    fontWeight: '900',
    lineHeight: 24,
  },
  resultHeader: {
    marginBottom: 20,
  },
  resultTitle: {
    color: '#17233a',
    fontSize: 31,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 37,
    marginTop: 10,
  },
  resultBlock: {
    backgroundColor: 'rgba(247,251,255,0.78)',
    borderRadius: 24,
    marginBottom: 12,
    padding: 18,
  },
  resultBlockTitle: {
    color: '#17233a',
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 8,
  },
  resultBody: {
    color: '#52627a',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 4,
  },
  reliefPanel: {
    backgroundColor: '#17233a',
    borderRadius: 26,
    marginTop: 4,
    padding: 20,
  },
  reliefEyebrow: {
    color: '#8fc0ff',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  reliefStep: {
    color: '#dbe8ff',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
  },
  notePanel: {
    backgroundColor: 'rgba(247,251,255,0.7)',
    borderRadius: 24,
    marginTop: 12,
    padding: 18,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  practiceItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(247,251,255,0.78)',
    borderRadius: 24,
    flexDirection: 'row',
    marginBottom: 12,
    padding: 16,
  },
  practiceCopy: {
    flex: 1,
    marginLeft: 4,
  },
  practiceMeta: {
    color: '#1976ee',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 8,
  },
  practiceActions: {
    alignItems: 'flex-end',
    gap: 8,
    marginLeft: 10,
  },
  practiceStartButton: {
    alignItems: 'center',
    backgroundColor: '#1976ee',
    borderRadius: 16,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  practiceStartText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '900',
  },
  practiceAnalyzeButton: {
    alignItems: 'center',
    backgroundColor: '#edf5ff',
    borderRadius: 16,
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  practiceAnalyzeText: {
    color: '#6e7d94',
    fontSize: 12,
    fontWeight: '800',
  },
  practiceHero: {
    backgroundColor: 'rgba(247,251,255,0.82)',
    borderRadius: 28,
    padding: 22,
  },
  practiceHeroTitle: {
    color: '#17233a',
    fontSize: 32,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 38,
  },
  practiceHeroDuration: {
    color: '#1976ee',
    fontSize: 15,
    fontWeight: '900',
    marginTop: 8,
  },
  practiceStepList: {
    gap: 12,
    marginTop: 16,
  },
  practiceStepItem: {
    alignItems: 'center',
    backgroundColor: 'rgba(247,251,255,0.78)',
    borderRadius: 22,
    flexDirection: 'row',
    padding: 16,
  },
  practiceStepNumber: {
    alignItems: 'center',
    backgroundColor: '#1976ee',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginRight: 12,
    width: 36,
  },
  practiceStepNumberText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
  },
  practiceStepText: {
    color: '#52627a',
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
  },
  authOverlay: {
    alignItems: 'center',
    backgroundColor: '#dcecff',
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    padding: 22,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 20,
  },
  authPanel: {
    backgroundColor: 'rgba(247,251,255,0.9)',
    borderRadius: 28,
    padding: 22,
    boxShadow: '0 16px 26px rgba(142,169,201,0.18)',
    width: '100%',
  },
  authTitle: {
    color: '#17233a',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 36,
    marginTop: 8,
  },
  authText: {
    color: '#63728a',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  authLoadingText: {
    color: '#63728a',
    fontSize: 15,
    fontWeight: '700',
    marginTop: 12,
    textAlign: 'center',
  },
  authBenefits: {
    backgroundColor: '#edf5ff',
    borderRadius: 20,
    marginTop: 18,
    padding: 14,
  },
  authBenefit: {
    color: '#52627a',
    fontSize: 14,
    lineHeight: 22,
  },
  authSwitch: {
    backgroundColor: '#e5edf8',
    borderRadius: 18,
    flexDirection: 'row',
    gap: 6,
    marginTop: 20,
    padding: 5,
  },
  authSwitchButton: {
    alignItems: 'center',
    borderRadius: 14,
    flex: 1,
    minHeight: 42,
    justifyContent: 'center',
  },
  authSwitchButtonActive: {
    backgroundColor: '#ffffff',
  },
  authSwitchText: {
    color: '#63728a',
    fontSize: 14,
    fontWeight: '800',
  },
  authSwitchTextActive: {
    color: '#17233a',
  },
  authInput: {
    backgroundColor: '#edf5ff',
    borderRadius: 18,
    color: '#17233a',
    fontSize: 16,
    marginTop: 12,
    minHeight: 54,
    paddingHorizontal: 16,
  },
  authMessage: {
    color: '#52627a',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 12,
  },
  resendButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 42,
    marginTop: 8,
  },
  resendButtonText: {
    color: '#1976ee',
    fontSize: 14,
    fontWeight: '800',
  },
  oauthDivider: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 20,
  },
  oauthLine: {
    backgroundColor: '#c8d7ea',
    flex: 1,
    height: 1,
  },
  oauthDividerText: {
    color: '#728098',
    fontSize: 12,
    fontWeight: '800',
  },
  oauthStack: {
    gap: 10,
    marginTop: 16,
  },
  oauthButton: {
    alignItems: 'center',
    backgroundColor: '#edf5ff',
    borderRadius: 18,
    minHeight: 50,
    justifyContent: 'center',
  },
  oauthButtonText: {
    color: '#17233a',
    fontSize: 15,
    fontWeight: '900',
  },
  authFootnote: {
    color: '#728098',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 14,
  },
  sheetOverlay: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 30,
  },
  sheetBackdrop: {
    backgroundColor: 'rgba(23,35,58,0.24)',
    flex: 1,
  },
  accountSheet: {
    backgroundColor: '#f7fbff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    bottom: 0,
    left: 0,
    padding: 22,
    paddingBottom: 34,
    position: 'absolute',
    right: 0,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#c8d7ea',
    borderRadius: 3,
    height: 5,
    marginBottom: 18,
    width: 46,
  },
  accountNote: {
    backgroundColor: '#edf5ff',
    borderRadius: 20,
    marginTop: 16,
    padding: 14,
  },
  accountNoteText: {
    color: '#52627a',
    fontSize: 14,
    lineHeight: 20,
  },
  safetyTitle: {
    color: '#9f3d21',
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 32,
  },
  safetySteps: {
    backgroundColor: '#fff2ed',
    borderRadius: 20,
    gap: 10,
    marginTop: 16,
    padding: 16,
  },
  safetyStep: {
    color: '#5f453c',
    fontSize: 14,
    lineHeight: 21,
  },
  safetyNote: {
    color: '#7a584d',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 14,
  },
  dangerButton: {
    alignItems: 'center',
    borderColor: '#ff9b72',
    borderRadius: 20,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 52,
  },
  dangerButtonText: {
    color: '#d65b36',
    fontSize: 15,
    fontWeight: '800',
  },
  bottomNav: {
    alignSelf: 'center',
    backgroundColor: '#1976ee',
    borderRadius: 34,
    bottom: 22,
    flexDirection: 'row',
    gap: 4,
    padding: 7,
    position: 'absolute',
    boxShadow: '0 14px 24px rgba(35,111,199,0.26)',
    maxWidth: 386,
    width: '88%',
  },
  navItem: {
    alignItems: 'center',
    borderRadius: 26,
    height: 52,
    justifyContent: 'center',
    flex: 1,
    paddingHorizontal: 4,
  },
  navItemActive: {
    backgroundColor: '#ffffff',
  },
  navText: {
    color: '#d8e8ff',
    fontSize: 11,
    fontWeight: '800',
  },
  navTextActive: {
    color: '#17233a',
  },
});
